function ruleList(items, activeIndex = -1) {
  return `
    <ul class="rule-list">
      ${items.map((item, index) => `<li${index === activeIndex ? ' class="active-rule"' : ""}>${item}</li>`).join("\n")}
    </ul>
  `;
}

const seedRules = [
  `Quiver \\(Q\\): a directed graph without loops or oriented 2-cycles.`,
  `<span class="seed-rule-label">Vertices of \\(Q\\) =</span>
    <span class="seed-vertex-decomposition">
      <span class="vertex-type-inline"><span class="vertex-symbol mutable-symbol"></span>mutable vertices</span>
      \\(\\sqcup\\)
      <span class="vertex-type-inline"><span class="vertex-symbol frozen-symbol"></span>frozen vertices</span>
    </span>`,
  `\\(\\mathbf{x}=(x_1,\\ldots,x_n)\\): algebraically independent variables over \\(\\mathbb C\\).`,
  `<span class="blue-term">Seed</span>: \\(\\Sigma=(\\mathbf{x},Q)\\).`
];

const mutationRules = [
  `Mutation is performed at a mutable vertex \\(k\\).`,
  `For each path \\(i\\to k\\to j\\), add \\(i\\to j\\).`,
  `Reverse all arrows incident to \\(k\\), then cancel oriented two-cycles.`,
  `Replace \\(x_k\\) by \\(x_k'\\) using:
    \\[
    x_kx_k'=\\prod_{i\\to k}x_i+\\prod_{k\\to j}x_j.
    \\]`,
  `Mutation is involutive.`
];

const patternRules = [
  `Mutation at each mutable vertex.`,
  `Regular graph of seeds.`,
  `Cluster variables: variables in the seeds.`,
  `<div class="field-ring-definitions">
    \\(\\mathfrak F:=\\mathbb C(x_1,\\ldots,x_n)\\)<br>
    \\(\\mathbb P:=\\mathbb C[x_i^{\\pm1}\\mid x_i\\text{ frozen}]\\)
  </div>`,
  `<div class="definition-block">
    <div class="definition-title">Definition (Fomin-Zelevinsky)</div>
    <div>
      <span class="blue-term">Cluster algebra</span> \\(\\calA(\\Sigma)\\):
      \\(\\mathbb P\\)-subalgebra of \\(\\mathfrak F\\), generated by cluster variables.
    </div>
  </div>`
];

const clusterSteps = [
  {
    frameTitle: "Seed",
    kicker: "",
    title: "",
    body: ruleList(seedRules),
    mode: "seed"
  },
  {
    frameTitle: "Mutation",
    kicker: "",
    title: "",
    body: ruleList(mutationRules, 0),
    mode: "focus"
  },
  {
    frameTitle: "Mutation",
    kicker: "",
    title: "",
    body: ruleList(mutationRules, 1),
    mode: "paths"
  },
  {
    frameTitle: "Mutation",
    kicker: "",
    title: "",
    body: ruleList(mutationRules, 2),
    mode: "quiver-mutated"
  },
  {
    frameTitle: "Mutation",
    kicker: "",
    title: "",
    body: ruleList(mutationRules, 3),
    mode: "variable-mutated"
  },
  {
    frameTitle: "Mutation",
    kicker: "",
    title: "",
    body: ruleList(mutationRules, 4),
    mode: "involutive"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules),
    mode: "involutive"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules, 0),
    mode: "one-step-sequence"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules, 1),
    mode: "one-step-expanded"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules, 2),
    mode: "pattern-variables"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules, 3),
    mode: "pattern-variables"
  },
  {
    frameTitle: "Cluster Algebra",
    kicker: "",
    title: "",
    body: ruleList(patternRules, 4),
    mode: "cluster-algebra"
  }
];

const frames = [
  { type: "title" },
  { type: "static", title: "Overview", slide: "overview-slide" },
  { type: "section", title: "Cluster Algebra" },
  ...clusterSteps.map((step) => ({ type: "cluster", ...step })),
  { type: "comparison", title: "Comparing Cluster Structures" },
  { type: "section", title: "Bosonic Extension" },
  { type: "static", title: "Bosonic Extension", slide: "bosonic-extension-slide" },
  { type: "static", title: "Positive Braid", slide: "braid-monoid-slide" },
  { type: "static", title: "The algebra \\(\\obbA_{\\C}(\\ttb)\\)", slide: "algebra-slide" },
  { type: "static", title: "i-boxes", slide: "ibox-slide" },
  { type: "static", title: "Localization", slide: "localization-slide" },
  { type: "static", title: "Admissible Chain", slide: "admissible-chain-slide", state: "chain-input" },
  { type: "static", title: "Admissible Chain", slide: "admissible-chain-slide", state: "chain-step-1" },
  { type: "static", title: "Admissible Chain", slide: "admissible-chain-slide", state: "chain-step-2" },
  { type: "static", title: "Admissible Chain", slide: "admissible-chain-slide", state: "chain-step-3" },
  { type: "static", title: "Admissible Chain", slide: "admissible-chain-slide", state: "chain-complete" },
  { type: "static", title: "Cluster algebra structure on \\(\\tobbA_{\\C}(\\ttb)\\)", slide: "seed-chain-slide", state: "seed-ibox" },
  { type: "static", title: "Cluster algebra structure on \\(\\tobbA_{\\C}(\\ttb)\\)", slide: "seed-chain-slide", state: "seed-quiver" },
  { type: "static", title: "Cluster algebra structure on \\(\\tobbA_{\\C}(\\ttb)\\)", slide: "seed-chain-slide", state: "seed-d" },
  { type: "static", title: "Cluster algebra structure on \\(\\tobbA_{\\C}(\\ttb)\\)", slide: "seed-chain-slide", state: "seed-theorem" },
  { type: "section", title: "Braid Variety" },
  { type: "static", title: "Braid Variety", slide: "braid-variety-setup-slide" },
  { type: "static", title: "Affine coordinates on braid varieties", slide: "braid-variety-properties-slide" },
  { type: "static", title: "Demazure weave", slide: "weaves-slide" },
  { type: "static", title: "<span class=\"frame-title-text\">Example in type A<sub>3</sub></span>", slide: "weave-example-slide", state: "paper-example" },
  { type: "static", title: "<span class=\"frame-title-text\">Example in type A<sub>3</sub></span>", slide: "weave-example-slide", state: "default-example" },
  { type: "static", title: "Cluster Structure on Braid Variety", slide: "braid-cluster-slide", state: "braid-weave" },
  { type: "static", title: "Cluster Structure on Braid Variety", slide: "braid-cluster-slide", state: "braid-quiver" },
  { type: "static", title: "Cluster Structure on Braid Variety", slide: "braid-cluster-slide", state: "braid-functions" },
  { type: "static", title: "Cluster Structure on Braid Variety", slide: "braid-cluster-slide", state: "braid-theorem" },
  { type: "static", title: "Two Cluster Algebra Structures", slide: "pre-comparison-summary-slide" },
  { type: "section", title: "Comparison Theorem" },
  { type: "static", title: "Setup for Comparison", slide: "comparison-setup-slide" },
  { type: "static", title: "Comparison Theorem", slide: "comparison-theorem-slide" },
  { type: "section", title: "Application" },
  { type: "static", title: "Quantum Affine Algebras", slide: "quantum-affine-slide" },
  { type: "static", title: "Affine Determinantial Modules", slide: "affine-corollary-slide" },
  { type: "static", title: "Example", slide: "affine-example-slide" },
  { type: "static", title: "Thank You", slide: "thank-you-slide" }
];

let currentStep = 0;

const els = {
  deck: document.getElementById("deck"),
  frameTitle: document.getElementById("frame-title"),
  titleSlide: document.getElementById("title-slide"),
  sectionSlide: document.getElementById("section-slide"),
  sectionHeading: document.getElementById("section-heading"),
  clusterSlide: document.getElementById("cluster-slide"),
  comparisonSlide: document.getElementById("comparison-slide"),
  staticSlides: Array.from(document.querySelectorAll(".static-slide")),
  footer: document.getElementById("slide-footer"),
  seedView: document.getElementById("seed-view"),
  originalSeed: document.getElementById("original-seed"),
  patternView: document.getElementById("pattern-view"),
  oneStepView: document.getElementById("one-step-view"),
  clusterVariableDisplay: document.getElementById("cluster-variable-display"),
  clusterAlgebraDisplay: document.getElementById("cluster-algebra-display"),
  node2: document.getElementById("node-2"),
  node2Text: document.getElementById("node-2-text"),
  path12: document.getElementById("path-12"),
  path23: document.getElementById("path-23"),
  path13: document.getElementById("path-13"),
  focusMutationLabel: document.getElementById("focus-mutation-label"),
  kicker: document.getElementById("step-kicker"),
  title: document.getElementById("step-title"),
  body: document.getElementById("step-body"),
  counter: document.getElementById("step-counter"),
  prev: document.getElementById("prev-step"),
  next: document.getElementById("next-step")
};

function syncBraidClusterExample() {
  const target = document.getElementById("braid-cluster-weave-copy");
  if (!target || target.childElementCount > 0) return;
  const source = document.querySelector("#weave-example-slide .default-example-figure");
  if (!source) return;
  const clone = source.cloneNode(true);
  clone.classList.add("braid-cluster-weave-figure");
  const svg = clone.querySelector(".default-weave-svg");
  if (svg) {
    svg.setAttribute("viewBox", "230 30 330 470");
  }
  target.replaceChildren(clone);
}

function syncPreComparisonSummary() {
  const chainTarget = document.getElementById("summary-chain-copy");
  if (chainTarget && chainTarget.childElementCount === 0) {
    const chainSource = document.querySelector("#seed-chain-slide .seed-source-chain");
    if (chainSource) {
      chainTarget.replaceChildren(chainSource.cloneNode(true));
    }
  }

  const weaveTarget = document.getElementById("summary-weave-copy");
  if (weaveTarget && weaveTarget.childElementCount === 0) {
    const weaveSource = document.querySelector("#weave-example-slide .default-example-figure");
    if (weaveSource) {
      const clone = weaveSource.cloneNode(true);
      const svg = clone.querySelector(".default-weave-svg");
      if (svg) {
        svg.setAttribute("viewBox", "230 30 330 470");
      }
      weaveTarget.replaceChildren(clone);
    }
  }
}

function constructionIframe() {
  return document.querySelector("#weave-construction-slide .wdelta-construction-embed");
}

function activeConstructionStep() {
  return frames[currentStep]?.slide === "weave-construction-slide";
}

function focusConstructionIframe() {
  const iframe = constructionIframe();
  if (!iframe) return;
  iframe.focus({ preventScroll: true });
  try {
    iframe.contentWindow?.focus();
  } catch (_) {
  }
}

function navigateConstructionIframe(direction, options = {}) {
  const iframe = constructionIframe();
  if (!iframe) return false;
  try {
    const api = iframe.contentWindow?.WDELTA_CONSTRUCTION;
    if (!api?.navigateScene) return false;
    const moved = api.navigateScene(direction, options);
    focusConstructionIframe();
    return moved !== false;
  } catch (_) {
    return false;
  }
}

function setArrowPath(path, d) {
  path.setAttribute("d", d);
}

function resetVisual() {
  els.clusterSlide.classList.remove("show-cluster-vars", "show-cluster-algebra");
  els.seedView.classList.remove("copy-layout", "mutation-layout", "involutive-layout", "variable-layout", "bridge-layout", "continuation-layout", "pattern-stage", "one-step-background", "one-step-continuous", "seed-graph-layout");
  els.patternView.classList.remove("visible", "edge-focus", "expanded", "collecting", "algebra");
  els.oneStepView.classList.remove("visible", "stage-mu1", "stage-mu13", "stage-sequence", "stage-full", "stage-expanded", "stage-variables", "stage-algebra");
  els.node2.classList.remove("focus-ring");
  els.path12.classList.remove("highlight-edge");
  els.path23.classList.remove("highlight-edge");
  els.path13.classList.remove("visible", "highlight-edge");
  els.focusMutationLabel.classList.remove("visible");

  setArrowPath(els.path12, "M 294 260 L 374 260");
  setArrowPath(els.path23, "M 454 260 L 534 260");
  setArrowPath(els.path13, "M 289 232 C 352 168 476 168 539 232");
  els.node2Text.innerHTML = 'x<tspan baseline-shift="sub" font-size="18">2</tspan>';
}

function compactOriginalSeed() {
}

function applyVisual(mode) {
  resetVisual();

  if (mode === "focus") {
    els.node2.classList.add("focus-ring");
    els.focusMutationLabel.classList.add("visible");
  }

  if (mode === "paths") {
    els.seedView.classList.add("copy-layout");
  }

  if (mode === "quiver-mutated") {
    compactOriginalSeed();
    els.seedView.classList.add("mutation-layout");
  }

  if (mode === "involutive") {
    compactOriginalSeed();
    els.seedView.classList.add("variable-layout", "involutive-layout");
  }

  if (mode === "variable-mutated") {
    compactOriginalSeed();
    els.seedView.classList.add("variable-layout");
  }

  if (mode === "one-step-sequence") {
    compactOriginalSeed();
    els.seedView.classList.add("variable-layout", "involutive-layout", "seed-graph-layout");
    els.oneStepView.classList.add("visible", "stage-sequence");
  }

  if (mode === "one-step-expanded") {
    els.seedView.classList.add("pattern-stage");
    els.oneStepView.classList.add("visible", "stage-full", "stage-expanded");
  }

  if (mode === "pattern-variables") {
    els.clusterSlide.classList.add("show-cluster-vars");
    els.seedView.classList.add("pattern-stage");
    els.oneStepView.classList.add("visible", "stage-full", "stage-expanded", "stage-variables");
  }

  if (mode === "cluster-algebra") {
    els.clusterSlide.classList.add("show-cluster-vars", "show-cluster-algebra");
    els.seedView.classList.add("pattern-stage");
    els.oneStepView.classList.add("visible", "stage-full", "stage-expanded", "stage-variables", "stage-algebra");
  }
}

function renderStep(index) {
  currentStep = Math.max(0, Math.min(frames.length - 1, index));
  const step = frames[currentStep];

  els.deck.classList.remove("mode-title", "mode-section", "mode-cluster", "mode-comparison", "mode-static");
  els.sectionSlide.classList.remove("show-motivation");
  els.staticSlides.forEach((slide) => {
    slide.classList.remove("active");
    slide.removeAttribute("data-state");
  });

  if (step.type === "title") {
    els.deck.classList.add("mode-title");
    resetVisual();
  }

  if (step.type === "section") {
    els.deck.classList.add("mode-section");
    els.sectionHeading.textContent = step.title;
    resetVisual();
  }

  if (step.type === "motivation") {
    els.deck.classList.add("mode-section");
    els.sectionHeading.textContent = step.title;
    els.sectionSlide.classList.add("show-motivation");
    resetVisual();
  }

  if (step.type === "cluster") {
    els.deck.classList.add("mode-cluster");
    els.frameTitle.textContent = step.frameTitle ?? step.title;
    els.kicker.textContent = step.kicker;
    els.title.textContent = step.title;
    els.body.innerHTML = step.body;
    applyVisual(step.mode);
  }

  if (step.type === "comparison") {
    els.deck.classList.add("mode-comparison");
    els.frameTitle.textContent = step.title;
    resetVisual();
  }

  if (step.type === "static") {
    els.deck.classList.add("mode-static");
    els.frameTitle.innerHTML = step.title;
    resetVisual();
    const target = document.getElementById(step.slide);
    target?.classList.add("active");
    if (target && step.state) {
      target.dataset.state = step.state;
    }
    if (step.slide === "braid-cluster-slide") {
      syncBraidClusterExample();
    }
    if (step.slide === "pre-comparison-summary-slide") {
      syncPreComparisonSummary();
    }
    if (step.slide === "weave-construction-slide") {
      window.setTimeout(focusConstructionIframe, 80);
    }
  }

  els.counter.textContent = `${currentStep + 1}/${frames.length}`;
  els.prev.disabled = currentStep === 0;
  els.next.disabled = currentStep === frames.length - 1;

  if (window.MathJax?.typesetPromise && step.type === "cluster") {
    const mathTargets = [els.body, els.clusterVariableDisplay, els.clusterAlgebraDisplay];
    window.MathJax.typesetClear?.(mathTargets);
    window.MathJax.typesetPromise(mathTargets).catch(() => {});
  }

  if (window.MathJax?.typesetPromise && step.type === "comparison") {
    window.MathJax.typesetClear?.([els.comparisonSlide]);
    window.MathJax.typesetPromise([els.comparisonSlide]).catch(() => {});
  }

  if (window.MathJax?.typesetPromise && step.type === "static") {
    const target = document.getElementById(step.slide);
    window.MathJax.typesetClear?.([target, els.frameTitle]);
    window.MathJax.typesetPromise([target, els.frameTitle]).catch(() => {});
  }

  if (window.MathJax?.typesetPromise && step.type === "title") {
    window.MathJax.typesetClear?.([els.titleSlide]);
    window.MathJax.typesetPromise([els.titleSlide]).catch(() => {});
  }
}

els.prev.addEventListener("click", () => renderStep(currentStep - 1));
els.next.addEventListener("click", () => renderStep(currentStep + 1));

let lastWheelStepAt = 0;
let wheelAccumulator = 0;
let wheelResetTimer = null;

window.addEventListener("keydown", (event) => {
  if (activeConstructionStep()) {
    if (event.key === "ArrowRight" || event.key === " " || event.key === "PageDown") {
      if (navigateConstructionIframe(1)) {
        event.preventDefault();
        return;
      }
      event.preventDefault();
      renderStep(currentStep + 1);
      return;
    }
    if (event.key === "ArrowLeft" || event.key === "PageUp") {
      if (navigateConstructionIframe(-1)) {
        event.preventDefault();
        return;
      }
      event.preventDefault();
      renderStep(currentStep - 1);
      return;
    }
  }
  if (event.key === "ArrowRight" || event.key === " " || event.key === "PageDown") {
    event.preventDefault();
    renderStep(currentStep + 1);
  }
  if (event.key === "ArrowLeft" || event.key === "PageUp") {
    event.preventDefault();
    renderStep(currentStep - 1);
  }
});

window.addEventListener("wheel", (event) => {
  const rawDelta = Math.abs(event.deltaY) >= Math.abs(event.deltaX) ? event.deltaY : event.deltaX;
  if (Math.abs(rawDelta) < 2) return;

  const now = performance.now();
  const modeScale = event.deltaMode === 1 ? 18 : event.deltaMode === 2 ? window.innerHeight : 1;
  const primaryDelta = rawDelta * modeScale;
  const direction = primaryDelta > 0 ? 1 : -1;
  const wheelThreshold = 70;
  const wheelCooldown = 120;

  event.preventDefault();

  if (wheelAccumulator && Math.sign(wheelAccumulator) !== direction) {
    wheelAccumulator = 0;
  }
  wheelAccumulator += primaryDelta;

  window.clearTimeout(wheelResetTimer);
  wheelResetTimer = window.setTimeout(() => {
    wheelAccumulator = 0;
  }, 360);

  if (Math.abs(wheelAccumulator) < wheelThreshold || now - lastWheelStepAt < wheelCooldown) {
    return;
  }

  lastWheelStepAt = now;
  const stepCount = Math.min(3, Math.floor(Math.abs(wheelAccumulator) / wheelThreshold));
  if (activeConstructionStep()) {
    wheelAccumulator -= direction * stepCount * wheelThreshold;
    if (navigateConstructionIframe(direction, {
      stepCount,
      speedMultiplier: 0.58,
      force: true
    })) {
      return;
    }
    renderStep(currentStep + direction);
    return;
  }

  wheelAccumulator -= direction * stepCount * wheelThreshold;
  renderStep(currentStep + direction * stepCount);
}, { passive: false });

window.addEventListener("message", (event) => {
  if (event.data?.type !== "wdelta-boundary") return;
  if (!activeConstructionStep()) return;
  const direction = event.data.direction > 0 ? 1 : -1;
  renderStep(currentStep + direction);
});

function initialStepFromUrl() {
  const params = new URLSearchParams(window.location.search);
  const value = Number.parseInt(params.get("step") ?? "1", 10);
  if (Number.isNaN(value)) return 0;
  return value - 1;
}

window.addEventListener("load", () => renderStep(initialStepFromUrl()));
renderStep(initialStepFromUrl());
